/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CleaningTeam } from "./CleaningTeam";
import { CleaningTeamCountArgs } from "./CleaningTeamCountArgs";
import { CleaningTeamFindManyArgs } from "./CleaningTeamFindManyArgs";
import { CleaningTeamFindUniqueArgs } from "./CleaningTeamFindUniqueArgs";
import { DeleteCleaningTeamArgs } from "./DeleteCleaningTeamArgs";
import { CleaningTeamService } from "../cleaningTeam.service";
@graphql.Resolver(() => CleaningTeam)
export class CleaningTeamResolverBase {
  constructor(protected readonly service: CleaningTeamService) {}

  async _cleaningTeamsMeta(
    @graphql.Args() args: CleaningTeamCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [CleaningTeam])
  async cleaningTeams(
    @graphql.Args() args: CleaningTeamFindManyArgs
  ): Promise<CleaningTeam[]> {
    return this.service.cleaningTeams(args);
  }

  @graphql.Query(() => CleaningTeam, { nullable: true })
  async cleaningTeam(
    @graphql.Args() args: CleaningTeamFindUniqueArgs
  ): Promise<CleaningTeam | null> {
    const result = await this.service.cleaningTeam(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => CleaningTeam)
  async deleteCleaningTeam(
    @graphql.Args() args: DeleteCleaningTeamArgs
  ): Promise<CleaningTeam | null> {
    try {
      return await this.service.deleteCleaningTeam(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
