/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Rent } from "./Rent";
import { RentCountArgs } from "./RentCountArgs";
import { RentFindManyArgs } from "./RentFindManyArgs";
import { RentFindUniqueArgs } from "./RentFindUniqueArgs";
import { DeleteRentArgs } from "./DeleteRentArgs";
import { RentService } from "../rent.service";
@graphql.Resolver(() => Rent)
export class RentResolverBase {
  constructor(protected readonly service: RentService) {}

  async _rentsMeta(
    @graphql.Args() args: RentCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Rent])
  async rents(@graphql.Args() args: RentFindManyArgs): Promise<Rent[]> {
    return this.service.rents(args);
  }

  @graphql.Query(() => Rent, { nullable: true })
  async rent(@graphql.Args() args: RentFindUniqueArgs): Promise<Rent | null> {
    const result = await this.service.rent(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Rent)
  async deleteRent(@graphql.Args() args: DeleteRentArgs): Promise<Rent | null> {
    try {
      return await this.service.deleteRent(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
